// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: base.proto

/*
Package dbagent is a generated protocol buffer package.

It is generated from these files:
	base.proto
	db_agent_server.proto
	test_user.proto

It has these top-level messages:
	Nil
	BoolValue
	IntValue
	StringValue
	KV
	StringList
	Int64List
	TestUser
	ListUser
*/
package dbagent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package
